[package]
name = "kumokara-workspace"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
kumokara-protocol.workspace = true
kumokara-event.workspace = true
sqlx.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
uuid.workspace = true
chrono.workspace = true
tracing.workspace = true
anyhow.workspace = true
thiserror.workspace = true
dirs.workspace = true
